### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by m1ci** [dbpedia/lookup#58]
I get following error when compiling (`mvn clean install`).
@sandroacoelho any idea on the cause of this error? Can you maybe try to compile it? Thanks!

Here is the error I get.

```
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:51)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:64)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.871 s
[INFO] Finished at: 2020-04-06T16:45:40+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (compile) on project dbpedia-lookup: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by sandroacoelho** [comment]
Hi @m1ci ,

Are you using Java 8? I ran it in Travis (https://travis-ci.org/github/dbpedia/lookup) and it works fine!

Best,

**Comment by m1ci** [comment]
Hm... it seems I was using Java 13. Let me try with Java 8.

**Comment by jiguangxi** [comment]
> Hm... it seems I was using Java 13. Let me try with Java 8.

Hi @m1ci ,
I also encountered the same mistake.  How did you do it?  In addition, I'm using Java 8。

**Comment by m1ci** [comment]
@sandroacoelho it works, I managed to compile it. Thus I'm clsing the issue.
